INSERT INTO Products VALUES
                         (1000,'Tomatoes',5000,100,null,true,'/get-image/Tomato.png',2),
                         (1001,'Cucumbers',7000,100,null,true,'/get-image/Cucumber.png',2),
                         (1002,'Milk', 10000, 200,null,true,'/get-image/Milk.png',3),
                         (1003,'Meat', 75000, 500,'Good meat',true,'/get-image/Meat.png',5),
                         (1004,'Bread', 2000, 100,null,true,'/get-image/Bread.png',7),
                         (1005,'Butter', 25000, 20,null,true,'/get-image/Butter.png',3),
                         (1006,'Cheese', 55000, 50,null,true,'/get-image/Cheese.png',3),
                         (1007,'Orange Juice', 11000, 120,null,true,'/get-image/Juice.png',4),
                         (1008,'Water', 3000, 90,null,true,'/get-image/Water.png',4),
                         (1009,'Fish', 65000, 30,null,true,'/get-image/Fish.png',5),
                         (1010,'Watermelon', 14000, 80,null,true,'/get-image/Watermelon.png',1),
                         (1011,'Garlic', 15000, 10,null,true,'/get-image/Garlic.png',2),
                         (1012,'Chocolate', 15000, 100,null,true,'/get-image/Chocolate.png',6),
                         (1013,'Alcohol', 35000, 70,null,true,'/get-image/Alcohol.png',4);

INSERT INTO Errors VALUES
                          (1, 1, 'en', 'User not found in base.'),
                          (2, 1, 'ru', 'Пользователь не найден в базе.'),
                          (3, 1, 'uz', 'Foydalanuvchi bazasida topilmadi.'),
                          (4, 2, 'en', 'Basket not found in base.'),
                          (5, 2, 'ru', 'Корзина не найден в базе.'),
                          (6, 2, 'uz', 'Savat bazasida topilmadi.'),
                          (7, 3, 'en', 'Product not found in base.'),
                          (8, 3, 'ru', 'Продукт не найден в базе.'),
                          (9, 3, 'uz', 'Mahsulot bazasida topilmadi.'),
                          (10, 4, 'en', 'Item weight exceeds stock by '),
                          (11, 4, 'ru', 'Вес товара превышает запас на '),
                            (12, 4, 'uz', 'Tovar vaznining zaxiradan oshagan miqdori '),
                            (13, 5, 'en', 'Product prohibited.'),
                          (14, 5, 'ru', 'Товар запрещен.'),
                            (15, 5, 'uz', 'Mahsulot taqiqlangan.'),
                          (16, 6, 'en', 'The product is over.'),
                          (17, 6, 'ru', 'Товар закончился.'),
                            (18, 6, 'uz', 'Mahsulot tugadi.'),
                          (19, 7, 'en', 'The user already has a card.'),
                          (20, 7, 'ru', 'У пользователя уже есть карта.'),
                            (21, 7, 'uz', 'Foydalanuvchi allaqachon kartaga ega.'),
                          (22, 8, 'en', 'Card not found in base.'),
                          (23, 8, 'ru', 'Карта не найдена в базе'),
                            (24, 8, 'uz', 'Karta bazasida topilmadi'),
                          (25, 9, 'en', 'Insufficient funds.'),
                          (26, 9, 'ru', 'Недостаточно средств.'),
                            (27, 9, 'uz', 'Etarli mablag yoq.'),
                          (28, 10, 'en', 'Wrong password.'),
                          (29, 10, 'ru', 'Неправильный пароль.'),
                            (30, 10, 'uz', 'Notogri parol.'),
                          (31, 11, 'en', 'The account has been deleted.'),
                          (32, 11, 'ru', 'Аккаунт был удален.'),
                            (33, 11, 'uz', 'Hisob ochirildi.'),
                          (34, 12, 'en', 'Last try.'),
                          (35, 12, 'ru', 'Последняя попытка.'),
                            (36, 12, 'uz', 'Oxirgi urinish.'),
                          (37, 13, 'en', 'The shopping list is empty.'),
                          (38, 13, 'ru', 'Список покупок пуст.'),
                            (39, 13, 'uz', 'Xaridlar royxati bosh.'),
                          (40,14, 'en', 'Not enough goods. Try specifying less.'),
                          (41, 14, 'ru', 'Недостаточно товара. Попробуйте указать меньше.'),
                            (42, 14, 'uz', 'Etarli mahsulot emas. Kamroq ishora qilib koring.');